add teleporter plugin
SIE-VR/demo1 pull request #4
Opened 2017-03-21 13:12 UTC by MoriatyC

add assert/teleporter

2017-03-21 13:23 UTC, MoriatyC commented
old iron double click 666

2017-03-22 01:53 UTC, Time1ess requested changes
* File hierarchy change.
* scene update.

2017-03-22 10:10 UTC, Time1ess requested changes
* Rollback changes on `env`

2017-03-22 10:35 UTC, Time1ess approved these changes

2017-03-22 10:35 UTC, merged